language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo" INCLUDE="opl_all"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
  - VERSION="7.0" ODOO_REPO="OCA/OCB" INCLUDE="opl_all"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/vauxoo-dev/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - ${TRAVIS_BUILD_DIR}/travis/travis_install_pe_nightly ${VERSION}

script:
  - travis_run_tests ${VERSION}

after_success:
  coveralls
